### ISSUE TITLE
Client build does not work on main as defined in README.md (actual main) 

### ISSUE THREAD

**Issue by pfostenberg** [eclipse-wakaama/wakaama#833] opened 2024-11-26 22:46 UTC
from the readme build shall be work like that.

```console
cmake -S examples/client -B build-client -DWAKAAMA_MODE_CLIENT=ON
cmake --build build-client
./build-client/lwm2mclient 
```

Client build does not work on main as defined in README.md

```
git clone --recurse-submodules https://github.com/eclipse/wakaama.git
Klone nach 'wakaama' …
remote: Enumerating objects: 9041, done.
remote: Counting objects: 100% (4496/4496), done.
remote: Compressing objects: 100% (790/790), done.
remote: Total 9041 (delta 3875), reused 3821 (delta 3643), pack-reused 4545 (from 1)
Empfange Objekte: 100% (9041/9041), 3.17 MiB | 10.81 MiB/s, fertig.
Löse Unterschiede auf: 100% (6454/6454), fertig.
Submodul 'platforms/Linux/tinydtls' (https://github.com/eclipse/tinydtls.git) für Pfad 'transport/tinydtls/third_party/tinydtls' in die Konfiguration eingetragen.
Klone nach '/home/mza/work/git/2024_11/wakaama/transport/tinydtls/third_party/tinydtls' …
remote: Enumerating objects: 4049, done.
remote: Counting objects: 100% (1397/1397), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 4049 (delta 1289), reused 1221 (delta 1215), pack-reused 2652 (from 1)
Empfange Objekte: 100% (4049/4049), 1.25 MiB | 10.04 MiB/s, fertig.
Löse Unterschiede auf: 100% (2864/2864), fertig.
Submodul-Pfad 'transport/tinydtls/third_party/tinydtls': '86f23c65ffde9d46b6487d2210d98d58a41257d5' ausgecheckt
```

then build the client.

```
cmake -S examples/client -B build-client -DWAKAAMA_MODE_CLIENT=ON
-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/mza/work/git/2024_11/wakaama/build-client
```

then:

```
cmake --build build-client
```

no error but no exe? the lib is there...

```
..
[100%] Linking C static library libwakaama_static.a
[100%] Built target wakaama_static

~/wakaama$ ls -lh ./build-client/lwm2mclient
ls: Zugriff auf './build-client/lwm2mclient' nicht möglich: Datei oder Verzeichnis nicht gefunden
```

Any idea?

BR

Andreas

**Comment by rettichschnidi** [comment] 2024-11-27 00:03
Can confirm.

The root cause is that this (fairly fully fledged) client gets built only under very specific conditions: https://github.com/eclipse-wakaama/wakaama/blob/ec4458bae7f65d68490df1cc11069ebe5b94e5ea/examples/client/CMakeLists.txt#L7

And those conditions are not the ones listed in the readme file. This needs to be fixed one way or another.

@LukasWoodtli Any reason we could not just lift all those restrictions and become closer to what e.g. https://github.com/eclipse-wakaama/wakaama/blob/main/examples/server/CMakeLists.txt contains?

**Comment by pfostenberg** [comment] 2024-11-27 07:31
I tried to remove the conditions from cMakeList.txt file in client...

  AND WAKAAMA_CLIENT_INITIATED_BOOTSTRAP
   AND WAKAAMA_DATA_SENML_JSON

a lot of compiler errors.

Also added the define in the cmake the command line ..
(but need to test without bootstrap..but gave it a try.)

also a lot of compiler errors.

is this only a problem at my system?
or is the build broken?

**Comment by LukasWoodtli** [comment] 2024-11-27 07:44
If you want to stay on 'main', you can try this:

```
cmake --preset client
cmake --build --preset client
build-presets/client/examples/client/lwm2mclient
```

**Comment by pfostenberg** [comment] 2024-11-27 21:27
thanx, this works now -:)

**Comment by LukasWoodtli** [comment] 2024-11-28 11:25
@pfostenberg Please be aware that #818 will be merged soon. Then the build of the client example will change slightly. But it should then work as documented.

**Comment by LukasWoodtli** [comment] 2024-11-28 11:26
Closing as there is a workaround and a fix.

**Closed by LukasWoodtli** 2024-11-28 11:26 UTC
